# Generated by Django 4.1 on 2022-09-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'classroom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discussroom',
            fields=[
                ('no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=30)),
                ('total_people', models.IntegerField()),
            ],
            options={
                'db_table': 'discussroom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discussroom_ans',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('datetime', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discussroom_ans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discussroom_question',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'discussroom_question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discussroom_record',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('datetime', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discussroom_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Impeach',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=1000)),
                ('datetime', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'impeach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pace', models.IntegerField()),
                ('datetime', models.DateField(blank=True, null=True)),
                ('ftime', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('settime_no', models.IntegerField()),
                ('entry_time', models.DateField(blank=True, null=True)),
                ('exit_time', models.DateField(blank=True, null=True)),
                ('total_time', models.DateField(blank=True, null=True)),
                ('subject_detail', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schoolsys',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'school_sys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settime',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
            ],
            options={
                'db_table': 'settime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studyroom',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('total_people', models.IntegerField()),
            ],
            options={
                'db_table': 'studyroom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Success',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('pace', models.IntegerField()),
            ],
            options={
                'db_table': 'success',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Success_list',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('pace', models.IntegerField()),
                ('lockif', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'success_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=5)),
                ('live', models.CharField(max_length=100)),
                ('photo', models.TextField(blank=True, null=True)),
                ('borth', models.DateField(blank=True, null=True)),
                ('purview', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
